pipeline:
  install:
    when:
      event: [push]
    image: node:12.14-alpine
    commands:
      - npm install
      - npx lerna bootstrap

  build:
    when:
      event: [push]
    image: node:12.14-alpine
    commands:
      - npx lerna run build

  publish:
    when:
      branch: master
    image: node:12.14-alpine
    secrets: [ "npm_token" ]
    commands:
      - npm -v
      - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - echo $NPM_TOKEN
      - npx lerna publish from-package --yes
