pipeline:
  install:
    when:
      event: [push]
    image: node:12.14-alpine
    commands:
      - npm install
      - npx lerna bootstrap

  build:
    when:
      event: [push]
    image: node:12.14-alpine
    commands:
      - npx lerna run build
